<Project Sdk="Microsoft.Build.NoTargets">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageProjectReference Include="..\Cogito.AspNetCore.ServiceModel\Cogito.AspNetCore.ServiceModel.csproj">
            <PackageTargetPath>.</PackageTargetPath>
        </PackageProjectReference>
    </ItemGroup>

</Project>
