install:
  - choco install gitversion.portable -pre -y

image: Visual Studio 2017

assembly_info:
  patch: false

init:
  - gitversion /l console /output buildserver
  - appveyor UpdateBuild -Version %
    

before_build:
  - ps: cd src\
  - nuget restore Cogito.AspNetCore.ServiceModel.sln
  - ps: gitversion /l console /output buildserver

build:
  project: Cogito.AspNetCore.ServiceModel.sln
